PROCESS BEFORE OUTPUT.
  MODULE status_0100.

  CALL SUBSCREEN sub1 INCLUDING sy-repid '0101'.
  CALL SUBSCREEN sub2 INCLUDING sy-repid '0102'.

PROCESS AFTER INPUT.
  MODULE user_command_0100.

  CALL SUBSCREEN sub1.
  CALL SUBSCREEN sub2.
